name: Hourly Crypto Updates

on:
  schedule:
    # Run every hour at minute 0
    - cron: "0 * * * *"

  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  send-crypto-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Send crypto updates
        run: node dist/index.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          COINGECKO_API_URL: ${{ secrets.COINGECKO_API_URL }}
